# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='标题')),
                ('link', models.CharField(default='', help_text="Cool URIs don't change", max_length=150, verbose_name='链接')),
                ('snippet', models.CharField(default='', max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '已发布')], default='d', max_length=1, verbose_name='状态')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('access_count', models.IntegerField(default=1, editable=False, verbose_name='浏览量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='名称')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='标签', null=True, to='blog.Tag', verbose_name='标签集合'),
        ),
    ]
